client_config_backend: settings
client_config:
  client_id: 934976480413-obb6th3bdfrc8lm7m66ickihnl5m9bjg.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install